Changes for enhanced logging for IUF used scripts

diff --git a/bin/iuf-skopeo-sync b/bin/iuf-skopeo-sync
--- a/bin/iuf-skopeo-sync
+++ b/bin/iuf-skopeo-sync
@@ -26,8 +26,8 @@
 shopt -s extglob
 
 usage(){
-    echo "Usage: $0 JSON_IUF_DOCKER_META"
-    echo "Uploads container images from the location(s) given by the JSON_IUF_DOCKER_META structure to the Nexus registry."
+    echo "INFO Usage: $0 JSON_IUF_DOCKER_META"
+    echo "INFO Uploads container images from the location(s) given by the JSON_IUF_DOCKER_META structure to the Nexus registry."
     exit 0 # Without error since the parameter may not have been included.
 }
 
@@ -56,20 +56,19 @@ trap 'ensure-results-file-exists $RESULTS_FILE' EXIT
 process(){
     docker_dir="$1"
     if [[ ! -d "/images/$docker_dir" ]]; then
-        echo "$0: Invalid directory $src"
-        echo "Skipping the skopeo sync operation for $docker_dir"
+        echo "ERROR $0: Invalid directory $src. Skipping the 'skopeo sync' operation for $docker_dir"
         return 1
     fi
 
     # Ensure $docker_dir ends with exactly one slash
     docker_dir="${docker_dir%%+(/)}/"
 
-    if skopeo sync --scoped \
+    result=$(skopeo sync --scoped \
         --src dir --dest docker \
         --dest-creds "${NEXUS_USERNAME:-admin}:${NEXUS_PASSWORD}" \
         --dest-tls-verify=false \
-        /images/"$docker_dir" "${NEXUS_REGISTRY:-registry.local}"; then
-
+        /images/"$docker_dir" "${NEXUS_REGISTRY:-registry.local}" 2>&1)         
+    if [ $? -eq 0 ]; then
         # Record results for each image. Note that we have to search the directory for
         # things that appear to be docker images here, which unfortunately is not directly
         # looking at the result of the `skopeo sync` command.
@@ -82,10 +81,12 @@ process(){
             image_dir="$(dirname "$relative_manifest_path")"
             image_name="$(cut -d":" -f 1 <<< "$image_dir")"
             image_version="$(cut -d":" -f 2 <<< "$image_dir")"
-            echo "INFO recording results for ${image_name}:${image_version}"
+            echo "INFO Adding entry in 'records.yaml' file for image: ${image_name}:${image_version}"
             record_result "$image_name" "$image_version"
         done
     else
+        result=$(echo "$result" | sed -e 's/^/DEBUG /')
+        echo -e "DEBUG <skopeo sync --scoped --src dir --dest docker --dest-creds "${NEXUS_USERNAME:-admin}:${NEXUS_PASSWORD}" --dest-tls-verify=false /images/"$docker_dir" "${NEXUS_REGISTRY:-registry.local}"> failed with\n\n$result"        
         return 1
     fi
 }
@@ -108,8 +109,8 @@ function record_result(){
 
 
 if [[ $# -eq 0 ]]; then
-    echo "Missing docker context from the IUF manifest."
-    echo "Skipping this operation."
+    echo "ERROR Docker context not passed from the IUF manifest. Skipping
+    running the 'iuf-skopeo-sync' script"
     usage
 fi
 
@@ -118,7 +119,7 @@ fi
 json_docker_context="$1"
 docker_dirs=$(echo "$json_docker_context" | jq '.docker | length')
 if [[ -z "$docker_dirs" ]]; then
-    echo "Did not receive any docker directory context."
+    echo "ERROR Docker directory context not received from IUF. Exiting"
     exit 0
 fi
 
@@ -126,11 +127,11 @@ exit_code=0
 for (( i=0; i<${docker_dirs}; i++ ));
 do
     path=$(echo "$json_docker_context" | jq -r '.docker['$i'].path')
-    echo "Processing docker images at $path"
+    echo "INFO Processing docker images in directory: $path"
     if ! process "$path"; then
         exit_code=1
     fi
 done
 
-echo "Exit code is ${exit_code}"
+echo "INFO 'iuf-skopeo-sync' script completed with exit code: ${exit_code}"
 exit $exit_code
diff --git a/bin/nexus-repositories-create b/bin/nexus-repositories-create
--- a/bin/nexus-repositories-create
+++ b/bin/nexus-repositories-create
@@ -23,17 +23,17 @@ function find_repo(){
     # If changes are needed, ensure that testing is done on both Nexus 3.25.0 (csm-1.2) and
     # 3.38.0 (csm-1.3) since this is used in both versions.
     if [[ $# -ne 3 ]]; then
-        echo -n >&2 "Missing arguments. Expecting repo_format repo_type repo_name. Arguments passed were: $@"
+        echo -n >&2 "ERROR Missing arguments. Expecting repo_format repo_type repo_name. Arguments passed were: $@"
         return 1
     fi
-    if [[ -z "$1" ]]; then echo -n >&2 "Empty repo_format argument."; return 1; fi
-    if [[ -z "$2" ]]; then echo -n >&2 "Empty repo_type argument."; return 1; fi
-    if [[ -z "$3" ]]; then echo -n >&2 "Empty repo_name argument."; return 1; fi
+    if [[ -z "$1" ]]; then echo -n >&2 "ERROR Empty repo_format argument"; return 1; fi
+    if [[ -z "$2" ]]; then echo -n >&2 "ERROR Empty repo_type argument"; return 1; fi
+    if [[ -z "$3" ]]; then echo -n >&2 "ERROR Empty repo_name argument"; return 1; fi
     repo_format=$1
     repo_type=$2
     repo_name=$3
 
-    echo -n >&2 "Looking for ${repo_format}/${repo_type} repository: ${repo_name}..."
+    echo -n >&2 "DEBUG Looking for ${repo_format}/${repo_type} repository: ${repo_name}..."
 
     # Ask Nexus for all repositories and filter that result by format, type, and name.
     jqfilter=".[] | select(.format == \"$repo_format\") | select(.type == \"$repo_type\") | select(.name == \"$repo_name\")"
@@ -41,10 +41,10 @@ function find_repo(){
 
     # An empty string here means that the repo was not found in the json result by format, type, and name.
     if [[ -z "$result" ]]; then
-      echo -n >&2 " NOT found..."
+      echo -n >&2 "ERROR Could not find the ${repo_format}/${repo_type} repository: ${repo_name}"
       return 1
     else
-      echo -n >&2 " Found..."
+      echo -n >&2 "INFO Found ${repo_format}/${repo_type} repository: ${repo_name}"
       return 0
     fi
 }
@@ -71,7 +71,7 @@ function record_result(){
 }
 
 while [[ $# -gt 0 ]]; do
-    echo "$0 processing $1"
+    echo "INFO $0: Processing $1"
     nrepos=$(yq r -d '*' -X -c -l "$1")
 
     for (( i=0; i<nrepos; i++ )); do
@@ -93,7 +93,7 @@ while [[ $# -gt 0 ]]; do
         if [[ $found -eq 1 ]]; then
             # Repo was not found, try to create it.
             # Don't call create on an existing repo (CASMINST-5136).
-            echo -n >&2 "Creating ${repo_format}/${repo_type} repository: ${repo_name}..."
+            echo -n >&2 "DEBUG Creating ${repo_format}/${repo_type} repository: ${repo_name}..."
             yq r -j "$tmpfile" | curl -sfk -w "%{http_code}" \
                 --retry-connrefused \
                 --retry "${CURL_RETRY:-36}" \
@@ -104,13 +104,13 @@ while [[ $# -gt 0 ]]; do
                 -d @-
             status=$?
             if [[ $status -eq 0 ]]; then
-                echo >&2 " OK created"
+                echo >&2 "INFO Successfully created ${repo_format}/${repo_type} repository: ${repo_name}"
             else
-                echo >&2 " FAIL"; exit $status;
+                echo >&2 "ERROR Failed to create ${repo_format}/${repo_type} repository: ${repo_name}"; exit $status;
             fi
         elif [[ $found -eq 0 ]]; then
             # Found the repo, try to update it.
-            echo -n >&2 "Updating ${repo_format}/${repo_type} repository: ${repo_name}..."
+            echo -n >&2 "DEBUG Updating ${repo_format}/${repo_type} repository: ${repo_name}..."
             yq r -j "$tmpfile" | curl -sfk -w "%{http_code}" \
                 --retry-connrefused \
                 --retry "${CURL_RETRY:-36}" \
@@ -121,13 +121,13 @@ while [[ $# -gt 0 ]]; do
                 -d @-
             status=$?
             if [[ $status -eq 0 ]]; then
-                echo >&2 " OK updated"
+                echo >&2 "INFO Successfully updated ${repo_format}/${repo_type} repository: ${repo_name}"
             else
-                echo >&2 " FAIL"; exit $status;
+                echo >&2 "ERROR Failed to update ${repo_format}/${repo_type} repository: ${repo_name}"; exit $status;
             fi
         else
             # We did not get a known response from the search API.
-            echo >&2 " FAIL due to unexpected http response $http_status"; exit 1
+            echo >&2 "ERROR Search for ${repo_format}/${repo_type} repository: ${repo_name} failed with unexpected response"; exit 1
         fi
         record_result "$repo_name" "$repo_type" "${repo_members[@]}"
     done
diff --git a/bin/nexus-upload-repo-yum b/bin/nexus-upload-repo-yum
--- a/bin/nexus-upload-repo-yum
+++ b/bin/nexus-upload-repo-yum
@@ -3,7 +3,7 @@
 # Copyright 2022 Hewlett Packard Enterprise Development LP
 
 if [[ $# -ne 2 ]]; then
-    echo >&2 "usage: ${0##*/} SRC-DIRECTORY DEST-REPOSITORY"
+    echo >&2 "INFO usage: ${0##*/} , two arguments required: SRC-DIRECTORY DEST-REPOSITORY "
     exit 1
 fi
 
@@ -12,11 +12,11 @@ repo="$2"
 shift 2
 
 if [[ ! -d "$path" ]]; then
-    echo >&2 "error: no such directory: $path"
+    echo >&2 "ERROR No such directory: $path"
     exit 1
 fi
 
-command -v parallel >/dev/null 2>&1 || { echo >&2 "command not found: parallel"; exit 1; }
+command -v parallel >/dev/null 2>&1 || { echo >&2 "ERROR 'parallel' command not found"; exit 1; }
 
 . "$(command -v nexus-ready)"
 
@@ -36,11 +36,11 @@ upload-asset-yum() {
             -F "yum.directory=$(dirname "$asset")" \
             -F "yum.asset.filename=$(basename "$asset")" \
             -F "yum.asset=@${file}")"
-        echo "$status"
+        echo "DEBUG <curl to URL  ${URL}/v1/components?repository=${repo}> completed with: $status"
         status="${status%% *}"
     done
 
-    if [[ "$status" = "204" ]]; then echo "created"; else echo "exists"; fi
+    if [[ "$status" = "204" ]]; then echo "INFO Repo created "; else echo "INFO Repo already exists"; fi
 }
 
 export URL path repo
@@ -51,3 +51,4 @@ find "$path" -name '*.rpm' -type f \
         "-j${PARALLEL_JOBS:-32}" \
         "${PARALLEL_FLAGS}" \
         upload-asset-yum
+
