Minor updates to support release tooling

diff --git a/bin/nexus-curl-auth b/bin/nexus-curl-auth
--- a/bin/nexus-curl-auth
+++ b/bin/nexus-curl-auth
@@ -2,28 +2,29 @@
 
 # Copyright 2022 Hewlett Packard Enterprise Development LP
 
-: "${NEXUS_URL:="http://localhost:8081"}"
 
-if [[ -v CURL_HOME ]]; then
-    if (return 0 2>/dev/null); then
-        return 0
-    else
-        echo >&2 "error: CURL_HOME is already set"
-        exit 1
-    fi
+if [[ $# -ne 1 ]]; then
+    echo >&2 "usage: ${0##*/} DIR"
+    exit 1
 fi
 
-export CURL_HOME="$(mktemp -d)"
-# Automatically clean-up temporary CURL_HOME directory if souroced
-(return 0 2>/dev/null) && trap "rm -fr '$CURL_HOME'" EXIT
+curl_home="$1"
+
+if [[ ! -d "$curl_home" ]]; then
+    echo >&2 "error: No such directory: $curl_home"
+    exit 1
+fi
+
+# Limit credentials to Nexus host if NEXUS_URL is set
+if [[ -v NEXUS_URL && -n "$NEXUS_URL" ]]; then
+    machine="machine $(sed -E -e 's_.*://([^/@]*@)?([^/:]+).*_\2_' <<< "$NEXUS_URL")"
+else
+    machine="default"
+fi
 
 # Add default Nexus admin credentials to netrc file
-NEXUS_HOST=$(sed -E -e 's_.*://([^/@]*@)?([^/:]+).*_\2_' <<< "$NEXUS_URL")
-echo "machine ${NEXUS_HOST} login ${NEXUS_USERNAME:-admin} password ${NEXUS_PASSWORD:-admin123}" > "${CURL_HOME}/.netrc"
-chmod u=r,go= "${CURL_HOME}/.netrc"
+echo "${machine} login ${NEXUS_USERNAME:-admin} password ${NEXUS_PASSWORD:-admin123}" > "${curl_home}/.netrc"
+chmod u=r,go= "${curl_home}/.netrc"
 
 # Configure curl to use netrc
-echo "--netrc-file ${CURL_HOME}/.netrc" > "${CURL_HOME}/.curlrc"
-
-# If not sourced, output CURL_HOME directory
-(return 0 2>/dev/null) || echo "$CURL_HOME"
+echo "--netrc-file ${curl_home}/.netrc" > "${curl_home}/.curlrc"
