CASMINST-6853 Logging in cray-setup-nexus scripts looks unreadable
This change partially reverts commit 4f0504c6847d6ce48c0c54b27138502d15067e98 in `bin/nexus-*` scripts.
Changes introduced with original commit make output from `bin/nexus-*` not quite readable,
and sometimes misleading (by reporting an error which is actually a check result rather then error):

    DEBUG Looking for raw/hosted repository: csm-1.6.0-imagesig.45-embedded ...ERROR Could not find the raw/hosted repository: csm-1.6.0-imagesig.45-embeddedDEBUG Creating raw/hosted repository: csm-1.6.0-imagesig.45-embedded ...301INFO Successfully created raw/hosted repository: csm-1.6.0-imagesig.45-embedded
    DEBUG Looking for raw/group repository: csm-embedded ...ERROR Could not find the raw/group repository: csm-embeddedDEBUG Creating raw/group repository: csm-embedded ...301INFO Successfully created raw/group repository: csm-embedded

diff --git a/bin/nexus-upload-repo-raw b/bin/nexus-upload-repo-raw
--- a/bin/nexus-upload-repo-raw
+++ b/bin/nexus-upload-repo-raw
@@ -3,7 +3,7 @@
 # Copyright 2022 Hewlett Packard Enterprise Development LP
 
 if [[ $# -ne 2 ]]; then
-    echo >&2 "Usage: ${0##*/} , two arguments required: SRC-DIRECTORY DEST-REPOSITORY"
+    echo >&2 "usage: ${0##*/} SRC-DIRECTORY DEST-REPOSITORY"
     exit 1
 fi
 
@@ -12,11 +12,11 @@ repo="$2"
 shift 2
 
 if [[ ! -d "$path" ]]; then
-    echo >&2 "ERROR  No such directory: $path"
+    echo >&2 "error: no such directory: $path"
     exit 1
 fi
 
-command -v parallel >/dev/null 2>&1 || { echo >&2 "ERROR 'parallel' command not found"; exit 1; }
+command -v parallel >/dev/null 2>&1 || { echo >&2 "command not found: parallel"; exit 1; }
 
 . "$(command -v nexus-ready)"
 
@@ -36,11 +36,11 @@ upload-asset-raw() {
             -F "raw.directory=$(dirname "$asset")" \
             -F "raw.asset1.filename=$(basename "$asset")" \
             -F "raw.asset1=@${file}")"
-        echo "DEBUG <curl to URL  ${URL}/v1/components?repository=${repo}> completed with: $status"
+        echo "$status"
         status="${status%% *}"
     done
 
-    if [[ "$status" = "204" ]]; then echo "INFO Repo created"; else echo "INFO Repo already exists, no action needed"; fi
+    if [[ "$status" = "204" ]]; then echo "created"; else echo "exists"; fi
 }
 
 export URL path repo
@@ -51,4 +51,3 @@ find "$path" -type f \
         "-j${PARALLEL_JOBS:-32}" \
         "${PARALLEL_FLAGS}" \
         upload-asset-raw
-
