CASMTRIAGE-7735: Add MAX_RETRY as base condition for while loop

diff --git a/bin/nexus-upload-repo-helm b/bin/nexus-upload-repo-helm
--- a/bin/nexus-upload-repo-helm
+++ b/bin/nexus-upload-repo-helm
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Copyright 2022 Hewlett Packard Enterprise Development LP
+# Copyright 2022-2025 Hewlett Packard Enterprise Development LP
 
 if [[ $# -ne 2 ]]; then
     echo >&2 "Usage: ${0##*/} SRC-DIRECTORY DEST-REPOSITORY"
@@ -26,7 +26,9 @@ upload-asset-helm() {
     asset="${asset#/}"
 
     status=""
-    while [[ "$status" != "204" && "$status" != "400" ]]; do
+    max_retry=3
+    retry_count=0
+    while [[ "$status" != "204" && "$status" != "400" ]] && [ $retry_count -lt $max_retry ]; do
         status="$(curl -sfk \
             --retry-connrefused \
             --retry "${CURL_RETRY:-36}" \
@@ -37,9 +39,17 @@ upload-asset-helm() {
             -F "helm.asset=@${file}")"
         echo "DEBUG <curl to URL  ${URL}/v1/components?repository=${repo}> completed with: $status"
         status="${status%% *}"
+        retry_count=$((RETRY_COUNT + 1))
     done
 
-    if [[ "$status" = "204" ]]; then echo "INFO Created repository ${repo}"; else echo "INFO Repository ${repo} already exists"; fi
+    if [[ "$status" = "204" ]]; then
+        echo "INFO Created repository ${repo}";
+    elif [[ "$status" = "400" ]]; then
+        echo "INFO Repository ${repo} already exists";
+    else
+        echo "ERROR Unable to Create Repository ${repo}, max attempts completed"
+        exit 1
+    fi
 }
 
 export URL path repo
