CASMISNT-5126 Prevent api calls to recreate an existing repository.

diff --git a/bin/nexus-repositories-create b/bin/nexus-repositories-create
--- a/bin/nexus-repositories-create
+++ b/bin/nexus-repositories-create
@@ -20,23 +20,30 @@ while [[ $# -gt 0 ]]; do
         repo_format="$(yq r "$tmpfile" 'format')"
         repo_type="$(yq r "$tmpfile" 'type')"
 
-        # First try to create
-        echo -n >&2 "Creating ${repo_format}/${repo_type} repository: ${repo_name}..."
-        yq r -j "$tmpfile" | curl -sfk -w "%{http_code}" \
-            --retry-connrefused \
-            --retry "${CURL_RETRY:-36}" \
-            --retry-delay "${CURL_RETRY_DELAY:-5}" \
-            --max-time "${CURL_MAX_TIME:-180}" \
-            -X POST "${URL}/beta/repositories/${repo_format}/${repo_type}" \
-            -H "Content-Type: application/json" \
-            -d @-
-        status=$?
-        if [[ $status -eq 0 ]]; then
-            echo >&2 " OK created"
-        else
-            echo >&2 " FAIL"
+        echo -n >&2 "Looking for ${repo_format}/${repo_type} repository: ${repo_name}..."
+        http_status=$(curl -sfk -w "%{http_code}" -o /dev/null \
+                  "${URL}/v1/repositories/${repo_format}/${repo_type}/${repo_name}")
 
-            # Failed to create, try to update
+        if [[ $http_status -eq 404 ]]; then
+            # Repo was not found, try to create it.
+            # Don't call ceate on an existing repo (CASMINST-5136).
+            echo -n >&2 "Creating ${repo_format}/${repo_type} repository: ${repo_name}..."
+            yq r -j "$tmpfile" | curl -sfk -w "%{http_code}" \
+                --retry-connrefused \
+                --retry "${CURL_RETRY:-36}" \
+                --retry-delay "${CURL_RETRY_DELAY:-5}" \
+                --max-time "${CURL_MAX_TIME:-180}" \
+                -X POST "${URL}/beta/repositories/${repo_format}/${repo_type}" \
+                -H "Content-Type: application/json" \
+                -d @-
+            status=$?
+            if [[ $status -eq 0 ]]; then
+                echo >&2 " OK created"
+            else
+                echo >&2 " FAIL"; exit $status;
+            fi
+        elif [[ $http_status -eq 200 ]]; then
+            # Found the repo, try to update it.
             echo -n >&2 "Updating ${repo_format}/${repo_type} repository: ${repo_name}..."
             yq r -j "$tmpfile" | curl -sfk -w "%{http_code}" \
                 --retry-connrefused \
@@ -52,6 +59,8 @@ while [[ $# -gt 0 ]]; do
             else
                 echo >&2 " FAIL"; exit $status;
             fi
+        else
+            echo >&2 " FAIL due to unexpected http response $http_status"; exit 1
         fi
     done
 
